### ISSUE TITLE
Translation Priorities 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2PLocalization-#3]
### Urgent

routerconsole
Website
readme
Router Status
welcome
I2P News
Core Library

### High
HTTP proxy error pages
manpages
Hidden Services Manager (i2ptunnel)
Web Server Help (eepsite) ***do we call this eepsite or I2P site? I think I2P site is easier to understand.
I2P Android
AddressBook (susidns)
I2P Android Helper Library

### Normal
System Tray ( Desktop GUI)
Website /misc/
Command line option errors (getopt)
Email (SusiMail)
Website/docs
I2PSnark Bittorrent Client
Streaming
itoopie-router control app
Router Startup Script (i2prouter)
Website /about/
Website /comparison/
Website /research/
Website /get-involved/
Website /blog/
countries
Debian Installer

**Comment by Shoalsteed** [comment]
Language outreach needs to consider router distribution as well as where there is a need for using I2P. This requires strategy for localization balance so that it supports building a greater anonymity set with more routers in regions where I2P does not face restrictions for operation.

To this end, focusing on localization efforts in French, Mandarin, and Portuguese can have a benefit for strengthening overall router distribution and creating a better opportunity for a increased anonymity for people who need to use I2P in more restricted regions.

Our current requested languages are:
Turkish
Russian (Traditional, Ukrainian) 
Greek 
Slovenian 
Spanish(Latin America) 
Turkmen

**Comment by eyedeekay** [comment]
I would just like to make the clarification that the hypothesis that French, Mandarin, and Portuguese are supportive of overall router geographic distribution is based on their being spoken in varying geographic regions. This is true enough for me to be satisfied that they should be a priority, but it's still at best a Wikipedia-informed guess.

I would describe the demand for Turkish and Russian translations on Transifex as fairly regular. I seem to get an email a week requesting Turkish translations, perhaps half that rate for Russian.

[This is the current Restrictive Countries list](https://geti2p.net/en/about/restrictive-countries).
