### ISSUE TITLE
infographics

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/I2PLocalization-#4]
![image](https://user-images.githubusercontent.com/50714166/160434911-c8f34f58-1b06-40fe-aba6-4813ef3b6b2d.png)

**Comment by Shoalsteed** [comment]
-what is the project
-what is the output ( protocol / network / tools)
-describe desktop 
-describe android

**Comment by Shoalsteed** [comment]
Project:
The Invisible Internet Project builds, deploys, and maintains a network supporting secure and anonymous communication.
The project has been in active development since early 2001. All of the work is open source, with the majority of the code released outright into the public domain, though making use of a few cryptographic routines under BSD-style licenses.

**Comment by Shoalsteed** [comment]
The Invisible Internet is a scalable, anonymizing network layer, upon which applications may make their own anonymity, latency, and throughput tradeoffs. Applications available already provide the full range of typical Internet activities - anonymous web browsing, web hosting, chat, file sharing, e-mail, blogging and content syndication, newsgroups, as well as several other applications under development.

**Comment by Shoalsteed** [comment]
![image](https://user-images.githubusercontent.com/50714166/160457930-2652defd-0711-4af9-949b-2ad6822388a8.png)

<img width="238" alt="image" src="https://user-images.githubusercontent.com/50714166/160457968-2079b65f-359e-4c20-be0b-f520b94c5689.png">

<img width="240" alt="image" src="https://user-images.githubusercontent.com/50714166/160457998-74a7c727-c564-4449-854f-c2ec92976fb7.png">

![image](https://user-images.githubusercontent.com/50714166/160458074-c239c952-9ec4-4df6-8ad4-d99f78e1dd01.png)

![image](https://user-images.githubusercontent.com/50714166/160458102-00e64bb6-6d29-4e67-b95b-04a2590682ed.png)

![image](https://user-images.githubusercontent.com/50714166/160458130-9941a924-d5de-496c-8dc2-e5af65962d85.png)

**Comment by Shoalsteed** [comment]
![I2PLocalization](https://user-images.githubusercontent.com/50714166/160485887-31cb5680-138d-400f-a435-0e3d3445954f.png)

**Comment by Shoalsteed** [comment]
***spacing issue in text

**Comment by Shoalsteed** [comment]
![I2PLocalization  (1)](https://user-images.githubusercontent.com/50714166/160486872-a8b7993c-5368-4d5b-9e1d-4d0068445d61.png)

**Comment by Shoalsteed** [comment]
![I2PLocalization  (1)](https://user-images.githubusercontent.com/50714166/160487075-3599b088-338a-4ede-9818-37f22479fe04.png)

**Comment by Shoalsteed** [comment]
![I2PLocalization  (1)](https://user-images.githubusercontent.com/50714166/160490224-32b50712-ca40-48ab-b220-4a78030612b8.png)

**Comment by Shoalsteed** [comment]
![I2P peer to peer](https://user-images.githubusercontent.com/50714166/161323196-5985e238-472c-4a1a-b6ee-93649f6bac4e.png)

**Comment by eyedeekay** [comment]
Some of these are looking pretty ready, is there somewhere you would like me to start putting them, like on the website or the subreddit or the wiki? All three?

**Comment by Shoalsteed** [comment]
I will create a separate repo for just infographics that we can use anywhere or refine for specific use.
